import { handleApiError } from '@/lib/api';
import axios from '@/services/axios.service';

/**
 * ADMIN  → all users
 * SUPERVISOR → all INTERN accounts
 */
export const getUsers = async (): Promise<User[]> => {
  try {
    const response = await axios.get('api/user/');
    return response.data.data;
  } catch (error) {
    return handleApiError(error);
  }
};

export const getUserById = async (id: string): Promise<User> => {
  try {
    const response = await axios.get(`api/user/${id}`);
    return response.data.data;
  } catch (error) {
    return handleApiError(error);
  }
};

/**
 * ADMIN → create SUPERVISOR or INTERN
 * SUPERVISOR → create INTERN only
 * Returns the created user and the temporary password generated by the server.
 */
export const createUser = async (
  data: CreateUserInput
): Promise<{ user: User; temporaryPassword: string }> => {
  try {
    const response = await axios.post('api/user', data);
    return response.data.data;
  } catch (error) {
    return handleApiError(error);
  }
};

export const updateUser = async (
  id: string,
  data: UpdateUserInput
): Promise<User> => {
  try {
    const response = await axios.patch(`api/user/${id}`, data);
    return response.data.data;
  } catch (error) {
    return handleApiError(error);
  }
};

export const updateUserRole = async (id: string, role: Role): Promise<User> => {
  try {
    const response = await axios.patch(`api/user/${id}/role`, { role });
    return response.data.data;
  } catch (error) {
    return handleApiError(error);
  }
};

/**
 * ADMIN only — activate or deactivate a user account.
 */
export const setUserActive = async (
  id: string,
  isActive: boolean
): Promise<User> => {
  try {
    const response = await axios.patch(`api/user/${id}/active`, { isActive });
    return response.data.data;
  } catch (error) {
    return handleApiError(error);
  }
};

export const deleteUser = async (id: string): Promise<void> => {
  try {
    await axios.delete(`api/user/${id}`);
  } catch (error) {
    return handleApiError(error);
  }
};
/**
 * DELETE /user/bulk
 * Returns counts of deleted and failed items (207 Multi-Status).
 */
export const bulkDeleteUsers = async (
  ids: string[]
): Promise<BulkDeleteResult> => {
  try {
    const response = await axios.delete('api/user/bulk', {
      data: { ids },
    });
    return response.data.data;
  } catch (error: any) {
    return handleApiError(error);
  }
};
