import { columns } from './columns';
import { DataTable } from './dataTable';

function getData(): Profile[] {
  return [
    {
      id: '728ed52f',
      userId: 'spiderweb123',
      pseudo: 'spiderweb',
      avatar: 'spider@mail.com',
      bio: 'this is the bio',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '728ed5IUYT2f',
      userId: 'spiderwebsup123',
      pseudo: 'spiderwesup',
      avatar: 'spidesupr@mail.com',
      bio: 'this is the  sup bio',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '728ed5IUYT2f',
      userId: 'spiderwebsup123',
      pseudo: 'spiderwesup',
      avatar: 'spidesupr@mail.com',
      bio: 'this is the  sup bio',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '728ed52f',
      userId: 'spiderweb123',
      pseudo: 'spiderweb',
      avatar: 'spider@mail.com',
      bio: 'this is the bio',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '728ed5IUYT2f',
      userId: 'spiderwebsup123',
      pseudo: 'spiderwesup',
      avatar: 'spidesupr@mail.com',
      bio: 'this is the  sup bio',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '728ed5IUYT2f',
      userId: 'spiderwebsup123',
      pseudo: 'spiderwesup',
      avatar: 'spidesupr@mail.com',
      bio: 'this is the  sup bio',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '728ed52f',
      userId: 'spiderweb123',
      pseudo: 'spiderweb',
      avatar: 'spider@mail.com',
      bio: 'this is the bio',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '728ed5IUYT2f',
      userId: 'spiderwebsup123',
      pseudo: 'spiderwesup',
      avatar: 'spidesupr@mail.com',
      bio: 'this is the  sup bio',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '728ed5IUYT2f',
      userId: 'spiderwebsup123',
      pseudo: 'spiderwesup',
      avatar: 'spidesupr@mail.com',
      bio: 'this is the  sup bio',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '728ed52f',
      userId: 'spiderweb123',
      pseudo: 'spiderweb',
      avatar: 'spider@mail.com',
      bio: 'this is the bio',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '728ed5IUYT2f',
      userId: 'spiderwebsup123',
      pseudo: 'spiderwesup',
      avatar: 'spidesupr@mail.com',
      bio: 'this is the  sup bio',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '728ed5IUYT2f',
      userId: 'spiderwebsup123',
      pseudo: 'spiderwesup',
      avatar: 'spidesupr@mail.com',
      bio: 'this is the  sup bio',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '728ed52f',
      userId: 'spiderweb123',
      pseudo: 'spiderweb',
      avatar: 'spider@mail.com',
      bio: 'this is the bio',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '728ed5IUYT2f',
      userId: 'spiderwebsup123',
      pseudo: 'spiderwesup',
      avatar: 'spidesupr@mail.com',
      bio: 'this is the  sup bio',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '728ed5IUYT2f',
      userId: 'spiderwebsup123',
      pseudo: 'spiderwesup',
      avatar: 'spidesupr@mail.com',
      bio: 'this is the  sup bio',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '728ed52f',
      userId: 'spiderweb123',
      pseudo: 'spiderweb',
      avatar: 'spider@mail.com',
      bio: 'this is the bio',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '728ed5IUYT2f',
      userId: 'spiderwebsup123',
      pseudo: 'spiderwesup',
      avatar: 'spidesupr@mail.com',
      bio: 'this is the  sup bio',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '728ed5IUYT2f',
      userId: 'spiderwebsup123',
      pseudo: 'spiderwesup',
      avatar: 'spidesupr@mail.com',
      bio: 'this is the  sup bio',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '728ed52f',
      userId: 'spiderweb123',
      pseudo: 'spiderweb',
      avatar: 'spider@mail.com',
      bio: 'this is the bio',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '728ed5IUYT2f',
      userId: 'spiderwebsup123',
      pseudo: 'spiderwesup',
      avatar: 'spidesupr@mail.com',
      bio: 'this is the  sup bio',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '728ed5IUYT2f',
      userId: 'spiderwebsup123',
      pseudo: 'spiderwesup',
      avatar: 'spidesupr@mail.com',
      bio: 'this is the  sup bio',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '728ed52f',
      userId: 'spiderweb123',
      pseudo: 'spiderweb',
      avatar: 'spider@mail.com',
      bio: 'this is the bio',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '728ed5IUYT2f',
      userId: 'spiderwebsup123',
      pseudo: 'spiderwesup',
      avatar: 'spidesupr@mail.com',
      bio: 'this is the  sup bio',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '728ed5IUYT2f',
      userId: 'spiderwebsup123',
      pseudo: 'spiderwesup',
      avatar: 'spidesupr@mail.com',
      bio: 'this is the  sup bio',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];
}

export default function userHandling() {
  const data = getData();

  return (
    <div className="container mx-auto py-10">
      <DataTable columns={columns} data={data} />
    </div>
  );
}
